### ISSUE TITLE
Not working on Sierra 10.12

### ISSUE THREAD

**Issue by ricardo85x** [theswiftdev/macos-launch-at-login-app#2]
Hi

Just downloaded, build, archive and install
But the MainApplication does not show up on Login Itens also it does not open on login.

**Comment by tib** [comment]
Hi,

i'll look after this, but it might takes some time because i don't have 10.12 installed right now.

**Comment by ricardo85x** [comment]
Hi
I found out the problem.
Your project is alright, the problem is on xcode.
The "App Sandbox" is checked, but I have to uncheck and check it to make it work.

**Comment by tib** [comment]
Xcode is drunk again... 🍻
