### ISSUE TITLE
Not work on menu bar app

### ISSUE THREAD

**Issue by ACChe** [theswiftdev/macos-launch-at-login-app#3]
Building an app that has no windows. It only own menu bar. This app has to be marked as an agent to hide the dock window. By follow this tutorial, it will never be launched by the helper.

**Comment by tib** [comment]
Hi, 

could you provide more info please... I'm using this method to launch a menu bar only application, so I can assure you this works for agent only apps as well.

Cheers,
Tib

**Comment by ACChe** [comment]
I followed tutorial step by step, and  the difference is I rename the Product name in "build settings".
While I run the app, set it to launch at login, quit the app , re-login macOS, but the menu bar app never start up after login to system. I open the Activity Monitor, helper process in the list, but sometimes cannot see both process display in the list.

**Comment by tib** [comment]
Did you change the application identifiers as well, inside both the launcher and the main AppDelegate.swift files? Is app sandboxing enabled with the proper entitlements? Is code signing working as it is expected?

**Comment by ACChe** [comment]
1 application identifiers is keep the same, I change the path name (`components.append("MainApplication") //main app`  in your project ) to my product name.
2 enabled sandbox 
3 code signing working well.

**Comment by tib** [comment]
What about the 

```swift
let mainAppIdentifier = "com.tiborbodecs.MainApplication"
```
and the

```swift
let launcherAppId = "com.tiborbodecs.LauncherApplication"
```

identifiers?

If those are correct as well, then I have no idea what's going on... but I'll investigate this later on.

**Comment by ACChe** [comment]
Both Identifiers in code are setup as same as bundle identifier in their target.
Sometimes I can find the helper app in the process, but the main app could not wake up.
Sometimes While I B and R the Xcode project , the main app run. There are 2 main app running.
Odd...

**Comment by tib** [comment]
> Both Identifiers in code are setup as same as bundle identifier in their target.

That's the problem, you have to setup the main id in the launcher, and the launcher id in the main...

**Comment by ACChe** [comment]
Sorry for my last comment with incorrect expression. I set main ID in the launcher and launcher ID in the main.

**Comment by ACChe** [comment]
@tib Hi, is there any method let me know whether the launcher app is set to loginItem successfully? Will the system file record this process?

**Comment by tib** [comment]
SMLoginItemSetEnabled returns a bool value, you can check that.

**Comment by ACChe** [comment]
After the app build out and run out of Xcode, it works.

**Comment by tib** [comment]
I'm glad that you could finally solve the issue.
